version: '3.7'
services:
  seafile:
    container_name: seafile
    build: .
    image: shaper-seafile
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      SEAFILE_URL: http://localhost
    volumes:
      # - $DATADIR/seafile:/seafile
      - $DATADIR/seafile/ccnet:/seafile/ccnet
      - $DATADIR/seafile/seafile-data:/seafile/seafile-data
      - $DATADIR/seafile/seahub-data:/seafile/seahub-data
      - $DATADIR/seafile/conf:/seafile/conf
      
  mariadb:
    container_name: mariadb
    networks:
      - default
    environment:
      MARIADB_ROOT_PASSWORD: secret
    image: mariadb:latest
    volumes:
      - $DATADIR/mysql:/var/lib/mysql

