version: '3.7'
services:
  seafile:
    container_name: seafile
    build: .
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      SEAFILE_URL: http://localhost
    volumes:
      - seafile/ccnet:/seafile/ccnet
      - seafile/seafile-data:/seafile/seafile-data
      - seafile/seahub-data:/seafile/seahub-data
      - seafile/conf:/seafile/conf
      
  mariadb:
    container_name: mariadb
    networks:
      - default
    environment:
      MARIADB_ROOT_PASSWORD: secret
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
  seafile:
    driver: local